favicon: /img/logo.png
apple_touch_icon: /img/logo.png
title_join_string: " | "
blog_logo: ''
blog_title: "Tao"
email_address: "2742400566@qq.com"
nickname: "ZhiZhen"

index:
  banner_img: /img/banner.png
  banner_img_height: 100
  banner_mask_alpha: 0.3
  grid_text: Hi,Xianghe!
  subtitle: You got to put the past behind you before you can move on.
  post_url_target: _self
  post_sticky:
    enable: true
    icon: 'iconfont icon-top'
  auto_excerpt:
    enable: true
  social_icon:
    - {class: "github", links: "https://github.com/XiangHeProject", tip: "GitHub"}
    - {class: "bilibili", links: "https://www.bilibili.com", tip: "BiliBili"}
    - {class: "zhihu", links: "https://www.zhihu.com", tip: "zhihu"}

notice:
  enable: true
  text: "2021/11/28: 开学了就先搞成这样等后续有时间继续完善"

nav:
  top_search: true
  shownav: true
  menu:
    - {key: "首页", link: "/", icon: "fa-fort-awesome faa-horizontal"}
    - {key: "归档", link: "/archives", icon: "fa-archive faa-shake"}

post:
  default_index_img: /img/3.png

footer:
  content: '
    “人不能一个人活下去，不需要任何人的孤独和需要人但得不到的孤独是不一样的。”
  '

lazyload:
  enable: true
  loading_img: /img/loading.gif
  onlypost: false
  offset_factor: 2

static_prefix:
  nprogress: https://cdn.jsdelivr.net/npm/nprogress@0.2.0/