favicon: /img/logo.png
apple_touch_icon: /img/logo.png
title_join_string: " | "

index:
  banner_img: /img/banner.png
  banner_img_height: 100
  banner_mask_alpha: 0.3
  grid_text: Hi,Xianghe!
  subtitle: You got to put the past behind you before you can move on.
  social_icon:
    - {class: "github", links: "https://github.com/XiangHeProject", tip: "GitHub"}
    - {class: "bilibili", links: "https://www.bilibili.com", tip: "BiliBili"}
    - {class: "zhihu", links: "https://www.zhihu.com", tip: "zhihu"}
    
    

footer:
  content: '
    “人不能一个人活下去，不需要任何人的孤独和需要人但得不到的孤独是不一样的。”
  '